import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight : ['400', '500', '600'],
  variable : '--font-poppins'
})

export const metadata: Metadata = {
  title: 'meet.com',
  description: 'Generated by create next app',
  icons : {
    icon : '/assets/images/io.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>{children}</body>
    </html>
  )
}
